server:
  port: 8081
  
spring:
  banner:
    location: banner.txt
    charset: UTF-8
  datasource:
    url: jdbc:postgresql://localhost:5432/wyzecmsdb
    username: dev
    password: dev
    driverClassName: org.postgresql.Driver
  main:
    web-application-type: reactive
    # hikari: schema: wyzecms
    # mvc:static-path-pattern: classpath:/static/,classpath:/templates/
    
  r2dbc:
    username: dev
    password: dev
    url: r2dbc:postgresql://localhost:5432/wyzecmsdb
    pool:
      enabled: true
      initial-size: 10
      max-size: 25
    
debug: true
