spring:
  banner:
    location: banner.txt
    charset: UTF-8
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All Tasks

debug: true
