server:
  port: 8085
spring:
  banner:
    location: banner.txt
    charset: UTF-8
  #mvc:static-path-pattern: classpath:/static/,classpath:/templates/
  web:
    resources:
      static-locations:
        - classpath:/static/
        - classpath:/templates/
        
debug: true
